#!/bin/bash

# notes folder, for note creation and limiting searches
NOTESDIR="/home/cagriemer/.notes"
# extension used for your notes
# example NOTESEXT=".md"
NOTESEXT=""
# the prefix you use to separate "Question" notes
NOTESPRE=""
# editor command to use for modifying answers
EDITOR="nano"

NOTESDIR=`echo $NOTESDIR|sed -e '/\/$/! s/$/\//'`

if [[ "$1" == "-h" ]]
then
appname=`basename $0`
  echo "$appname: build a knowledgebase with plain text files"
  echo "Find an answer: $appname \"terms to search for\""
  echo "Add a question\answer: $appname -a \"Question in natural language\" \"Succinct answer\""
  echo "Add a question\answer interactively: $appname -a"
  echo "Edit a question\answer: $appname -e \"terms to search for\" # first question found is edited"

elif [[ "$1" = "-l" ]]
then
ls -t1 $NOTESDIR | nl
elif [[ "$1" = "-r" ]]
then
shift
INPUT=$@
find "$NOTESDIR" -name "$INPUT" -exec rm -rf {} \;
elif [[ "$1" == "-a" ]]
then
if [ $# == 3 ]; then
QUESTION=$2
    ANSWER=$3
  elif [ $# == 1 ]; then
echo -n "Question: "
    read QUESTION
    echo -n "Answer: "
    read ANSWER
  else
echo "Invalid number of arguments for -a(dd). Requires question and answer (or no arguments to input them at runtime)."
    echo "example: ${0##*/} -a \"What is the meaning of life?\" \"42\""
    exit 1
  fi
echo -n "$ANSWER" > "$NOTESDIR$NOTESPRE$QUESTION$NOTESEXT" && echo "Question added and answered." || echo "Something went wrong"
elif [[ "$1" == "-e" ]]; then
shift
INPUT=$@
  ANSWER=`find "$NOTESDIR" -name "$INPUT"|head -n 1`
  if [[ "$ANSWER" == "" ]]; then
echo "No results found for search."
    exit 2
  else
    $EDITOR "$ANSWER"
  fi
else
INPUT=$@
  echo "`find "$NOTESDIR" -name "$INPUT"`"|while read LINE; do
if [[ "$LINE" == "" ]]; then
echo "Sorry, I don't know the answer to that question."
        exit 1;
      fi
QUESTION=${LINE##*/}
      echo -n "Q: "
      NOTESPREESC=`echo "$NOTESPRE"|sed -E 's/([\?\!\$\`\"]) ?/\\\\\1/g'`
#      echo ${QUESTION%%$NOTESEXT}|sed -E "s/$NOTESPREESC ?//g"|sed -E 's/(.)$/\1?/'
      echo $QUESTION
      echo -n "A: "
      cat "$LINE"|sed -E 's/@\([^\)]+\) ?//g'|sed -E 's/@copy\(([^)]*)\)/\1/'|sed -E 's/@open\(([^)]*)\)/Related URL: \1/'|sed -E 's/^[ ]*|[ ]*$//g'
      if [[ `cat "$LINE"|grep -E '@copy\('` ]]; then
cat "$LINE"|grep '@copy('|sed -E 's/.*@copy\(([^)]*)\).*/\1/'|tr -d '\n'|xclip -selection clipboard
        echo -e "\nExample in clipboard"
      fi

if [[ `cat "$LINE"|grep -E '@open\('` ]]; then
url=$(cat "$LINE"|grep '@open('|sed -E 's/.*@open\(([^)]*)\).*/\1 /'|tr -d '\n')
        firefox -new-window $url
        echo -e "\nOpened URL"
      fi
echo
done
fi
exit 0
