#!/bin/bash

# TODO: implement @copy() and @open()

# notes directory
NOTESDIR="$HOME/.notes"

# text editor
EDITOR="nano"

function usage()
{
echo -e "\n\tQUICK QUESTIONS HELP"
echo -e "\t<note_name> to see that note"
echo -e "\t-a to add note"
echo -e "\t-e <note_name> to edit a note"
echo -e "\t-l to list all notes"
echo -e "\t-r <note_name> to remove a note"
echo -e "\t-h to print this help\n"
exit 0
}

[[ ! $1 ]] && usage

if [[ $1 ]] && [[ "$1" != -* ]]
then
	echo "$(find $NOTESDIR -name $1)" | while read LINE
	do
		if [[ "$LINE" == "" ]]
		then
			echo "Sorry, I don't know the answer."
			exit 1
		fi
		QUESTION=$(basename "$LINE")
		echo -n "Q: "
		echo $QUESTION
		echo -n "A: "
		FANCYANSWER=$(cat "$LINE" | egrep -c "@copy\(|@open\(")
		if [[ "$FANCYANSWER" == "0" ]]
		then
			cat "$LINE"
			echo
		else
			echo "fancy"
		fi
	done
fi 

while getopts ":ae:r:lh" opt
do
	case "$opt" in
		a)
			echo -n "Question: "
			read QUESTION
			echo -n "Answer: "
			read ANSWER
			echo -n "$ANSWER" > "$NOTESDIR/$QUESTION" && echo "Question added."
			exit 0
		;;

		e)
			ANSWER=$(find "$NOTESDIR" -name "$OPTARG" | head -n 1)
			if [[ "$ANSWER" == "" ]]
			then
				echo "No results found for search."
				exit 1
			else
				$EDITOR "$ANSWER"
			fi
		;;

		r)
			find $NOTESDIR -name $OPTARG -exec rm -rfi {} \;
			exit 0
		;;

		l)
			ls -t1 $NOTESDIR | nl
			exit 0
		;;

		h)
			usage
		;;

		\?)
			echo -e "\n-$OPTARG is not a recognized option."
			usage
		;;

		:)
			echo -e "\n-$OPTARG needs an argument."
			usage
		;;
	esac
done

